trigger:
- none
name: Rename SQLServer Database

variables:
  vmImageName: 'ubuntu-latest'
  SqlServer: 'groomut-dbserver-ctc.database.windows.net' # SQL Serverのホスト名またはIPアドレスを設定します
  SqlUser: 'azureuser' # SQL Serverのユーザー名を設定します
  SqlPassword: 'Passw0rd!' # SQL Serverのパスワードを設定します
  Database: 'groomut-db' # データベース名を設定します
  RenameDatabase: 'groomut-db-renamed' # 変更後データベース名を設定します

pool:
  vmImage: $(vmImageName)

steps:
# SQLCMDをインストール
- script: |
    sudo apt-get update
    sudo apt-get install -y mssql-tools unixodbc-dev
    echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
    source ~/.bashrc

# SQL Serverに接続し、DB名変更クエリを実行する
- script: |
    sqlcmd -S $(SqlServer) -U $(SqlUser) -P $(SqlPassword) -d master -Q "ALTER DATABASE [$(Database)] MODIFY NAME = [$(RenameDatabase)];"
